# Generated by Django 5.2.10 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_author_alter_comment_post'),
        ('core_user', '0003_user_posts_liked_alter_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_comment.comment'),
        ),
    ]
